# Workflow for the data mining, filling and examining procedure

```{mermaid}
sequenceDiagram
    box 1. Data Mining
    participant spikes
    participant technical Error
    end
    box 2. Data Filling
    participant small Gaps
    participant big Gaps
    end
    box 3. Data Quality Examing
    participant PM10
    participant PM2.5
    end
    loop Spikecheck and technical error
        spikes->spikes: Detect spikes: pm10 and pm2.5 > 7 mg/m3
        technical Error->technical Error: Whether mistakenly pm10<pm2.5
    end
    loop check 3-hour max gaps
        small Gaps->small Gaps: Fill with the imputeTS package
    end
    Note right of small Gaps: For the package univariation,  <br/> we used log function.
    loop Fill large gaps
    big Gaps->big Gaps: MTSDI method
    end
    Note right of big Gaps: uses  <br/>ARIMA(p,d,q)
    PM10->PM2.5: plot(PM10,PM2.5)
```

## Data mining
Missing data We examined the PM data quality, and removed spikes those are above 7 
, and when PM10,,. Due to electricity shortage and equipment malfunctions contributed to the bad data, and missing data. In Sainshand station, … was … Each stations has some features, we treated each stations separately to remove suspective data.


## Data filling 

Missing data handling with the statistical packages At last, we filled the missing data with 3-hour maxgaps with imputeTS package for univariate time series, and larger gaps using mtsdi R package (well-used for time-series data), and improved the missing data percents by… from … to … Additionally, meteorological parameters such as wind speed, direction, and visibility are integrated into the analysis to elucidate their impact on PM levels.

The MTSDI method (Junger, Santos, and Ponce de Leon (2003), Junger and Leon (2012)) uses the EM algorithm with the Autoregressive Integrated Moving Average (ARIMA) method, also known as Box–Jenkins model (Box et al. (2015), Meyler, Kenny, and Quinn (1998)). The data provided by ARIMA (p, d, q) depend on the number of autoregressive terms (p), the number of differences (d), and the number of terms in the moving average (q) (Meyler, Kenny, and Quinn (1998)). Default configuration was used. The mtdsi method is widely used to impute missing data like in cosmic data Fernandes, Lucio, and Fernandez (2017). Similar multiple imputation methods have been applied for multivariate solar data Zhang et al. (2020), highly univariate seasonal data even with the large amount of missing data Chaudhry et al. (2019), missin data imputation and modeling for leaching processes He et al. (2017). Recently, Motesaddi Zarandi et al. (2022) used the mtdsi method to imputing missing data air pollution in Tehran (We used the complete data of temperature (°C), relative humidity (RH) (%), wind speed (m/s), barometric pressure (BP) (mbar), PM10, PM2.5, NO2, CO, and CVD variables to impute SO2 and O3 with the mtdsi R package.).

## Data quality examining
